//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ossendorf.Csla.DataPortalExtensionGenerator.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ossendorf.Csla.DataPortalExtensionGenerator.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data portal method should not be used. Instead the type and compile safe extension method from the data portal extension generator should be used..
        /// </summary>
        internal static string DPEG1000Description {
            get {
                return ResourceManager.GetString("DPEG1000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data portal method &apos;{0}&apos; should not be used. Use a generated extension method instead..
        /// </summary>
        internal static string DPEG1000MessageFormat {
            get {
                return ResourceManager.GetString("DPEG1000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csla data portal method is used.
        /// </summary>
        internal static string DPEG1000Title {
            get {
                return ResourceManager.GetString("DPEG1000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The portal method must inject any IDataPortal or IChildDataPortal paramters instead of accepting it as normal parameter..
        /// </summary>
        internal static string DPEG1001Description {
            get {
                return ResourceManager.GetString("DPEG1001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter must be injected. Add the [Inject] attribute to the parameter..
        /// </summary>
        internal static string DPEG1001MessageFormat {
            get {
                return ResourceManager.GetString("DPEG1001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I(Child)DataPortal must be injected.
        /// </summary>
        internal static string DPEG1001Title {
            get {
                return ResourceManager.GetString("DPEG1001Title", resourceCulture);
            }
        }
    }
}
