//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ossendorf.Csla.DataPortalExtensionGenerator.Analyzers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ossendorf.Csla.DataPortalExtensionGenerator.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DPEG1000Description {
            get {
                return ResourceManager.GetString("DPEG1000Description", resourceCulture);
            }
        }
        
        internal static string DPEG1000MessageFormat {
            get {
                return ResourceManager.GetString("DPEG1000MessageFormat", resourceCulture);
            }
        }
        
        internal static string DPEG1000Title {
            get {
                return ResourceManager.GetString("DPEG1000Title", resourceCulture);
            }
        }
        
        internal static string DPEG1001Description {
            get {
                return ResourceManager.GetString("DPEG1001Description", resourceCulture);
            }
        }
        
        internal static string DPEG1001MessageFormat {
            get {
                return ResourceManager.GetString("DPEG1001MessageFormat", resourceCulture);
            }
        }
        
        internal static string DPEG1001Title {
            get {
                return ResourceManager.GetString("DPEG1001Title", resourceCulture);
            }
        }
        
        internal static string DPEG1002Description {
            get {
                return ResourceManager.GetString("DPEG1002Description", resourceCulture);
            }
        }
        
        internal static string DPEG1002MessageFormat {
            get {
                return ResourceManager.GetString("DPEG1002MessageFormat", resourceCulture);
            }
        }
        
        internal static string DPEG1002Title {
            get {
                return ResourceManager.GetString("DPEG1002Title", resourceCulture);
            }
        }
    }
}
