// <auto-generated />
#pragma warning disable 1591 // publicly visible type or member must be documented
#nullable enable

namespace Ossendorf.Csla.DataPortalExtensionGenerator;

/// <summary>
/// Place on partial static class to generate the data portal extensions.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
[global::System.Diagnostics.Conditional("DATAPORTAL_EXTENSIONS_USAGES")]
public sealed class DataPortalExtensionsAttribute : Attribute;