// <auto-generated />
#pragma warning disable 1591 // publicly visible type or member must be documented
#nullable enable

namespace Ossendorf.Csla.DataPortalExtensionGenerator;

/// <summary>
/// Place on a CSLA portal method to exclude it from data portal extension generation.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
public sealed class GenerateNoDataPortalExtensionAttribute : Attribute;
