//HintName: GeneratorTests.DataPortalExtensions_Fetch.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams.InnerDummy> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams.InnerDummy> __dpeg_source) => __dpeg_source.FetchAsync();
    }
}
