//HintName: GeneratorTests.DataPortalExtensions_Create.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::ExecuteTests.DummyCmd> CreateTest(this global::Csla.IDataPortal<global::ExecuteTests.DummyCmd> __dpeg_source, int a, string x) => __dpeg_source.CreateAsync(a, x);
    }
}
