//HintName: GeneratorTests2.DataPortalExtensions2_Fetch.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests2
{
    static partial class DataPortalExtensions2
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams> __dpeg_source, int krznbf) => __dpeg_source.FetchAsync(krznbf);
    }
}
