//HintName: GeneratorTests.DataPortalExtensions_Fetch.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams> __dpeg_source, string a, int b = 1, global::System.Collections.Generic.List<string>? list = null, string? x = null, string z = "") => __dpeg_source.FetchAsync(a, b, list, x, z);
    }
}
