//HintName: GeneratorTests.DataPortalExtensions.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated by the Ossendorf.Csla.DataPortalExtensionsGenerators source generator.")]
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams.InnerDummy> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams.InnerDummy> __dpeg_source) => __dpeg_source.FetchAsync();
    }
}
