//HintName: GeneratorTests.DataPortalExtensions_Execute.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::ExecuteTests.DummyCmd> ExecuteWithParameters(this global::Csla.IDataPortal<global::ExecuteTests.DummyCmd> __dpeg_source, string x, int y) => __dpeg_source.ExecuteAsync(x, y);
    }
}
