//HintName: GeneratorTests2.DataPortalExtensions2.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests2
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated by the Ossendorf.Csla.DataPortalExtensionsGenerators source generator.")]
    static partial class DataPortalExtensions2
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams> portal, int krznbf) => portal.FetchAsync(krznbf);
    }
}
