//HintName: GeneratorTests.DataPortalExtensions_ExecuteCommand.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::ExecuteTests.DummyCmd> ExecuteWithParameters(this global::Csla.IDataPortal<global::ExecuteTests.DummyCmd> __dpeg_source, global::ExecuteTests.DummyCmd __dpeg_command) => __dpeg_source.ExecuteAsync(__dpeg_command);
    }
}
