//HintName: GeneratorTests.DataPortalExtensions_Fetch.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams> __dpeg_source, global::TestEnum.SomeEnum krznbf = global::TestEnum.SomeEnum.Some) => __dpeg_source.FetchAsync(krznbf);
    }
}
