//HintName: GeneratorTests.DataPortalExtensions_Execute.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::ExecuteTests.DummyCmd> ExecuteWithoutParameters(this global::Csla.IDataPortal<global::ExecuteTests.DummyCmd> __dpeg_source) => __dpeg_source.ExecuteAsync();
    }
}
