//HintName: GeneratorTests.DataPortalExtensions_Delete.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task Foo(this global::Csla.IDataPortal<global::VerifyTests.DummyBO> __dpeg_source) => __dpeg_source.DeleteAsync();
    }
}
