//HintName: GeneratorTests.DataPortalExtensions_Fetch.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams> __dpeg_source, int? id, string krznbf, decimal reference, string abcdefg = "") => __dpeg_source.FetchAsync(id, krznbf, reference, abcdefg);
    }
}
