//HintName: GeneratorTests.DataPortalExtensions.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated by the Ossendorf.Csla.DataPortalExtensionsGenerators source generator.")]
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBO> Foo(this global::Csla.IDataPortal<global::VerifyTests.DummyBO> __dpeg_source) => __dpeg_source.ExecuteAsync();
    }
}
