//HintName: GeneratorTests.DataPortalExtensions_FetchChild.g.cs
// <auto-generated />
#nullable enable

namespace GeneratorTests
{
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBO> Foo(this global::Csla.IChildDataPortal<global::VerifyTests.DummyBO> __dpeg_source) => __dpeg_source.FetchChildAsync();
    }
}
