//HintName: GeneratorTests.DataPortalExtensions.g.cs
// <auto-generated />

namespace GeneratorTests
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated by the Ossendorf.Csla.DataPortalExtensionsGenerators source generator.")]
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams> portal, int? id, global::MyTest.Greats.Foo.Bar krznbf, decimal reference) => portal.FetchAsync(id, krznbf, reference);
    }
}
