//HintName: GeneratorTests.DataPortalExtensions.g.cs
// <auto-generated />

namespace GeneratorTests
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated by the Ossendorf.Csla.DataPortalExtensionsGenerators source generator.")]
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams> portal, string a, int b = 1, global::System.Collections.Generic.List<global::System.String> list = null, string x = null) => portal.FetchAsync(a, b, list, x);
    }
}
