//HintName: GeneratorTests.DataPortalExtensions.g.cs
// <auto-generated />

namespace GeneratorTests
{
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated by the Ossendorf.Csla.DataPortalExtensionsGenerators source generator.")]
    static partial class DataPortalExtensions
    {
        public static global::System.Threading.Tasks.Task<global::VerifyTests.DummyBOWithParams> Bar(this global::Csla.IDataPortal<global::VerifyTests.DummyBOWithParams> portal, global::System.Collections.Generic.IEnumerable<global::System.Guid> krznbf) => portal.FetchAsync(krznbf);
    }
}
