namespace Ossendorf.Csla.DataPortalExtensionGenerator;
internal static class GeneratorHelper {

    public const string FullyQalifiedNameOfMarkerAttribute = "Ossendorf.Csla.DataPortalExtensionGenerator.DataPortalExtensionsAttribute";

    public const string MarkerAttributeNameWithSuffix = "DataPortalExtensionsAttribute";
    public const string MarkerAttributeNameWithoutSuffix = "DataPortalExtensions";

    public static string VersionString { get; } = typeof(DataPortalExtensionGenerator)
                                                    .Assembly.GetCustomAttributes(typeof(System.Reflection.AssemblyInformationalVersionAttribute), true)
                                                    .Cast<System.Reflection.AssemblyInformationalVersionAttribute>().SingleOrDefault()?.InformationalVersion ??
                                                    typeof(DataPortalExtensionGenerator).Assembly.GetName().Version.ToString();

    public static readonly string MarkerAttribute = $@"// <auto-generated />

namespace Ossendorf.Csla.DataPortalExtensionGenerator {{

    /// <summary>
    /// Add to a partial static class which will hold the generated IDataPortal extensions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode(""Ossendorf.Csla.DataportalExtensionsGenerator"", ""{VersionString}"")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = ""Generated by the  Ossendorf.Csla.DataPortalExtensionsGenerators source generator."")]
    [global::System.AttributeUsage(System.AttributeTargets.Class)]
    public class {MarkerAttributeNameWithSuffix} : global::System.Attribute {{
    }}
}}";

    private static readonly Dictionary<string, DataPortalMethod> _methodTranslations = [];
    static GeneratorHelper() {
        foreach (var portalMethod in Enum.GetValues(typeof(DataPortalMethod)).Cast<DataPortalMethod>()) {
            _methodTranslations.Add(portalMethod.ToStringFast(), portalMethod);
            _methodTranslations.Add($"{portalMethod.ToStringFast()}Attribute", portalMethod);
        }
    }

    public static IReadOnlyDictionary<string, DataPortalMethod> RecognizedCslaDataPortalAttributes = _methodTranslations;
}